# Generated by Django 3.2.19 on 2023-05-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_ground', '0002_alter_reservation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['-time_slot'],
            },
        ),
    ]
