# Generated by Django 3.2.19 on 2023-05-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_ground', '0003_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['room'],
            },
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['time_slot']},
        ),
    ]
