# Generated by Django 3.2.19 on 2023-05-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_ground', '0004_auto_20230505_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
