# Generated by Django 3.2.19 on 2023-05-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_ground', '0005_reservation_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
