# Generated by Django 3.2.19 on 2023-05-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_ground', '0007_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='room',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
